import { FC } from 'react';
import Head from 'next/head';
import { Inter } from 'next/font/google';

import { NavBar } from '../Navbar';
import styles from './MainLayout.module.css';


const inter = Inter({ subsets: ['latin'] });


export const MainLayout: FC<{ children: JSX.Element }> = ({ children }) => {
  return (
    <>
      <Head>
        <title>Home</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <NavBar />

      <main className={`${styles.main} ${inter.className}`}>

        { children }

      </main>
    </>
  )
}
